version: "3.9"

services:
  redis:
    image: "redis:alpine"
    command: redis-server
    ports:
      - "6379:6379"

  lambda:
    build:
      context: .
      dockerfile: deploy/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env