AWSTemplateFormatVersion: '2010-09-09'
Description: An ECR repo for DogChecker images.
Parameters:
  RepoName:
    Type: String
Resources:
  Repo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref RepoName
      LifecyclePolicy:
        LifecyclePolicyText: '{"rules":[{"rulePriority":1,"description":"Keep only ten images total","selection":{"tagStatus":"any","countType":"imageCountMoreThan","countNumber":10},"action":{"type":"expire"}}]}'