AWSTemplateFormatVersion: '2010-09-09'
Description: A lambda that calls the Petfinder API, caches results, and emails any new dogs.
Parameters:
  FunctionName:
    Type: String
  ImageUri:
    Type: String
  Environment:
    Type: String
  PetfinderClientId:
    Type: String
  PetfinderClientSecret:
    Type: String
  RedisUrl:
    Type: String
  RedisPassword:
    Type: String
  MailerApiKey:
    Type: String
  MailerToName:
    Type: String
  MailerToAddress:
    Type: String
  MailerFromName:
    Type: String
  MailerFromAddress:
    Type: String

Resources:
  Lambda:
    Type: AWS::Lambda::Function
    Properties:
      PackageType: Image
      FunctionName: !Ref FunctionName
      Role:
        Fn::GetAtt:
          - Role
          - Arn
      ImageUri: !Ref ImageUri
      Timeout: 300
      Variables:
        ENVIRONMENT: !Ref Environment
        PETFINDER_CLIENT_ID: !Ref PetfinderClientId
        PETFINDER_CLIENT_SECRET: !Ref PetfinderClientSecret
        REDIS_URL: !Ref RedisUrl
        REDIS_PASSWORD: !Ref RedisPassword
        MAILER_API_KEY: !Ref MailerApiKey
        MAILER_TO_NAME: !Ref MailerToName
        MAILER_TO_ADDRESS: !Ref MailerToAddress
        MAILER_FROM_NAME: !Ref MailerFromName
        MAILER_FROM_ADDRESS: !Ref MailerFromAddress
  Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: DogCheckerRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: AWSLambdaBasicExecutionRole
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'