name: Create ECR Repository

on:
  workflow_dispatch:
    inputs:
      RepoName:
        description: "Name your ECR repo"
        required: true
        default: "dogchecker"

jobs:
  create-repo:
    name: Create ECR repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy CloudFormation Stack
        id: dogchecker-repo-stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: dogchecker-repo
          template: ./deploy/cloudformation/container-repo.yaml
          no-fail-on-empty-changeset: "1"
          parameter-overrides: >-
            RepoName: ${{inputs.RepoName}}